# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SudokuRllrRP.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QComboBox,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QLayout, QMainWindow, QPushButton, QSizePolicy,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(973, 463)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setBaseSize(QSize(500, 0))
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 10, 954, 297))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.tableWidget_2 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_2.columnCount() < 3):
            self.tableWidget_2.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.tableWidget_2.rowCount() < 3):
            self.tableWidget_2.setRowCount(3)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, __qtablewidgetitem14)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy1)
        self.tableWidget_2.setMinimumSize(QSize(0, 0))
        self.tableWidget_2.setMaximumSize(QSize(301, 91))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_2.setPalette(palette)
        self.tableWidget_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_2.setIconSize(QSize(0, 0))
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_2, 0, 1, 1, 1)

        self.tableWidget_7 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_7.columnCount() < 3):
            self.tableWidget_7.setColumnCount(3)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, __qtablewidgetitem17)
        if (self.tableWidget_7.rowCount() < 3):
            self.tableWidget_7.setRowCount(3)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(0, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(1, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(2, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget_7.setItem(0, 0, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget_7.setItem(0, 1, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidget_7.setItem(0, 2, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableWidget_7.setItem(1, 0, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableWidget_7.setItem(1, 1, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidget_7.setItem(1, 2, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableWidget_7.setItem(2, 0, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableWidget_7.setItem(2, 1, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableWidget_7.setItem(2, 2, __qtablewidgetitem29)
        self.tableWidget_7.setObjectName(u"tableWidget_7")
        sizePolicy1.setHeightForWidth(self.tableWidget_7.sizePolicy().hasHeightForWidth())
        self.tableWidget_7.setSizePolicy(sizePolicy1)
        self.tableWidget_7.setMinimumSize(QSize(0, 0))
        self.tableWidget_7.setMaximumSize(QSize(301, 91))
        palette1 = QPalette()
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_7.setPalette(palette1)
        self.tableWidget_7.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_7.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_7.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_7.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_7.setIconSize(QSize(0, 0))
        self.tableWidget_7.horizontalHeader().setVisible(False)
        self.tableWidget_7.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_7.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_7.verticalHeader().setVisible(False)
        self.tableWidget_7.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_7.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_7, 2, 0, 1, 1)

        self.tableWidget_8 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_8.columnCount() < 3):
            self.tableWidget_8.setColumnCount(3)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, __qtablewidgetitem32)
        if (self.tableWidget_8.rowCount() < 3):
            self.tableWidget_8.setRowCount(3)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(1, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(2, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.tableWidget_8.setItem(0, 0, __qtablewidgetitem36)
        __qtablewidgetitem37 = QTableWidgetItem()
        self.tableWidget_8.setItem(0, 1, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.tableWidget_8.setItem(0, 2, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.tableWidget_8.setItem(1, 0, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.tableWidget_8.setItem(1, 1, __qtablewidgetitem40)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.tableWidget_8.setItem(1, 2, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.tableWidget_8.setItem(2, 0, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.tableWidget_8.setItem(2, 1, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.tableWidget_8.setItem(2, 2, __qtablewidgetitem44)
        self.tableWidget_8.setObjectName(u"tableWidget_8")
        sizePolicy1.setHeightForWidth(self.tableWidget_8.sizePolicy().hasHeightForWidth())
        self.tableWidget_8.setSizePolicy(sizePolicy1)
        self.tableWidget_8.setMinimumSize(QSize(0, 0))
        self.tableWidget_8.setMaximumSize(QSize(301, 91))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_8.setPalette(palette2)
        self.tableWidget_8.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_8.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_8.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_8.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_8.setIconSize(QSize(0, 0))
        self.tableWidget_8.horizontalHeader().setVisible(False)
        self.tableWidget_8.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_8.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_8.verticalHeader().setVisible(False)
        self.tableWidget_8.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_8.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_8, 2, 1, 1, 1)

        self.tableWidget_3 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_3.columnCount() < 3):
            self.tableWidget_3.setColumnCount(3)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem45)
        __qtablewidgetitem46 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem46)
        __qtablewidgetitem47 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem47)
        if (self.tableWidget_3.rowCount() < 3):
            self.tableWidget_3.setRowCount(3)
        __qtablewidgetitem48 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, __qtablewidgetitem48)
        __qtablewidgetitem49 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, __qtablewidgetitem49)
        __qtablewidgetitem50 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, __qtablewidgetitem50)
        __qtablewidgetitem51 = QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, __qtablewidgetitem51)
        __qtablewidgetitem52 = QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, __qtablewidgetitem52)
        __qtablewidgetitem53 = QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, __qtablewidgetitem53)
        __qtablewidgetitem54 = QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, __qtablewidgetitem54)
        __qtablewidgetitem55 = QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, __qtablewidgetitem55)
        __qtablewidgetitem56 = QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, __qtablewidgetitem56)
        __qtablewidgetitem57 = QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, __qtablewidgetitem57)
        __qtablewidgetitem58 = QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, __qtablewidgetitem58)
        __qtablewidgetitem59 = QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, __qtablewidgetitem59)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy2)
        self.tableWidget_3.setMinimumSize(QSize(0, 0))
        self.tableWidget_3.setMaximumSize(QSize(301, 91))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_3.setPalette(palette3)
        self.tableWidget_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_3.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_3.setIconSize(QSize(0, 0))
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_3, 0, 2, 1, 1)

        self.tableWidget_5 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_5.columnCount() < 3):
            self.tableWidget_5.setColumnCount(3)
        __qtablewidgetitem60 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem60)
        __qtablewidgetitem61 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, __qtablewidgetitem61)
        __qtablewidgetitem62 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, __qtablewidgetitem62)
        if (self.tableWidget_5.rowCount() < 3):
            self.tableWidget_5.setRowCount(3)
        __qtablewidgetitem63 = QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, __qtablewidgetitem63)
        __qtablewidgetitem64 = QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, __qtablewidgetitem64)
        __qtablewidgetitem65 = QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, __qtablewidgetitem65)
        __qtablewidgetitem66 = QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, __qtablewidgetitem66)
        __qtablewidgetitem67 = QTableWidgetItem()
        self.tableWidget_5.setItem(0, 1, __qtablewidgetitem67)
        __qtablewidgetitem68 = QTableWidgetItem()
        self.tableWidget_5.setItem(0, 2, __qtablewidgetitem68)
        __qtablewidgetitem69 = QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, __qtablewidgetitem69)
        __qtablewidgetitem70 = QTableWidgetItem()
        self.tableWidget_5.setItem(1, 1, __qtablewidgetitem70)
        __qtablewidgetitem71 = QTableWidgetItem()
        self.tableWidget_5.setItem(1, 2, __qtablewidgetitem71)
        __qtablewidgetitem72 = QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, __qtablewidgetitem72)
        __qtablewidgetitem73 = QTableWidgetItem()
        self.tableWidget_5.setItem(2, 1, __qtablewidgetitem73)
        __qtablewidgetitem74 = QTableWidgetItem()
        self.tableWidget_5.setItem(2, 2, __qtablewidgetitem74)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        sizePolicy1.setHeightForWidth(self.tableWidget_5.sizePolicy().hasHeightForWidth())
        self.tableWidget_5.setSizePolicy(sizePolicy1)
        self.tableWidget_5.setMinimumSize(QSize(0, 0))
        self.tableWidget_5.setMaximumSize(QSize(301, 91))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_5.setPalette(palette4)
        self.tableWidget_5.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_5.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_5.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_5.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_5.setIconSize(QSize(0, 0))
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_5.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tableWidget_5.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_5.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_5, 1, 1, 1, 1)

        self.tableWidget = QTableWidget(self.layoutWidget)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        __qtablewidgetitem75 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem75)
        __qtablewidgetitem76 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem76)
        __qtablewidgetitem77 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem77)
        if (self.tableWidget.rowCount() < 3):
            self.tableWidget.setRowCount(3)
        __qtablewidgetitem78 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem78)
        __qtablewidgetitem79 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem79)
        __qtablewidgetitem80 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem80)
        __qtablewidgetitem81 = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, __qtablewidgetitem81)
        __qtablewidgetitem82 = QTableWidgetItem()
        self.tableWidget.setItem(0, 1, __qtablewidgetitem82)
        __qtablewidgetitem83 = QTableWidgetItem()
        self.tableWidget.setItem(0, 2, __qtablewidgetitem83)
        __qtablewidgetitem84 = QTableWidgetItem()
        self.tableWidget.setItem(1, 0, __qtablewidgetitem84)
        __qtablewidgetitem85 = QTableWidgetItem()
        self.tableWidget.setItem(1, 1, __qtablewidgetitem85)
        __qtablewidgetitem86 = QTableWidgetItem()
        self.tableWidget.setItem(1, 2, __qtablewidgetitem86)
        __qtablewidgetitem87 = QTableWidgetItem()
        self.tableWidget.setItem(2, 0, __qtablewidgetitem87)
        __qtablewidgetitem88 = QTableWidgetItem()
        self.tableWidget.setItem(2, 1, __qtablewidgetitem88)
        __qtablewidgetitem89 = QTableWidgetItem()
        self.tableWidget.setItem(2, 2, __qtablewidgetitem89)
        self.tableWidget.setObjectName(u"tableWidget")
        sizePolicy1.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy1)
        self.tableWidget.setMinimumSize(QSize(0, 0))
        self.tableWidget.setMaximumSize(QSize(301, 91))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget.setPalette(palette5)
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget.setIconSize(QSize(0, 0))
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.tableWidget_6 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_6.columnCount() < 3):
            self.tableWidget_6.setColumnCount(3)
        __qtablewidgetitem90 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, __qtablewidgetitem90)
        __qtablewidgetitem91 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, __qtablewidgetitem91)
        __qtablewidgetitem92 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, __qtablewidgetitem92)
        if (self.tableWidget_6.rowCount() < 3):
            self.tableWidget_6.setRowCount(3)
        __qtablewidgetitem93 = QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, __qtablewidgetitem93)
        __qtablewidgetitem94 = QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, __qtablewidgetitem94)
        __qtablewidgetitem95 = QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, __qtablewidgetitem95)
        __qtablewidgetitem96 = QTableWidgetItem()
        self.tableWidget_6.setItem(0, 0, __qtablewidgetitem96)
        __qtablewidgetitem97 = QTableWidgetItem()
        self.tableWidget_6.setItem(0, 1, __qtablewidgetitem97)
        __qtablewidgetitem98 = QTableWidgetItem()
        self.tableWidget_6.setItem(0, 2, __qtablewidgetitem98)
        __qtablewidgetitem99 = QTableWidgetItem()
        self.tableWidget_6.setItem(1, 0, __qtablewidgetitem99)
        __qtablewidgetitem100 = QTableWidgetItem()
        self.tableWidget_6.setItem(1, 1, __qtablewidgetitem100)
        __qtablewidgetitem101 = QTableWidgetItem()
        self.tableWidget_6.setItem(1, 2, __qtablewidgetitem101)
        __qtablewidgetitem102 = QTableWidgetItem()
        self.tableWidget_6.setItem(2, 0, __qtablewidgetitem102)
        __qtablewidgetitem103 = QTableWidgetItem()
        self.tableWidget_6.setItem(2, 1, __qtablewidgetitem103)
        __qtablewidgetitem104 = QTableWidgetItem()
        self.tableWidget_6.setItem(2, 2, __qtablewidgetitem104)
        self.tableWidget_6.setObjectName(u"tableWidget_6")
        sizePolicy2.setHeightForWidth(self.tableWidget_6.sizePolicy().hasHeightForWidth())
        self.tableWidget_6.setSizePolicy(sizePolicy2)
        self.tableWidget_6.setMinimumSize(QSize(0, 0))
        self.tableWidget_6.setMaximumSize(QSize(301, 91))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_6.setPalette(palette6)
        self.tableWidget_6.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_6.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_6.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_6.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_6.setIconSize(QSize(0, 0))
        self.tableWidget_6.horizontalHeader().setVisible(False)
        self.tableWidget_6.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_6.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_6.verticalHeader().setVisible(False)
        self.tableWidget_6.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_6.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_6, 1, 2, 1, 1)

        self.tableWidget_9 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_9.columnCount() < 3):
            self.tableWidget_9.setColumnCount(3)
        __qtablewidgetitem105 = QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, __qtablewidgetitem105)
        __qtablewidgetitem106 = QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, __qtablewidgetitem106)
        __qtablewidgetitem107 = QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, __qtablewidgetitem107)
        if (self.tableWidget_9.rowCount() < 3):
            self.tableWidget_9.setRowCount(3)
        __qtablewidgetitem108 = QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(0, __qtablewidgetitem108)
        __qtablewidgetitem109 = QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(1, __qtablewidgetitem109)
        __qtablewidgetitem110 = QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(2, __qtablewidgetitem110)
        __qtablewidgetitem111 = QTableWidgetItem()
        self.tableWidget_9.setItem(0, 0, __qtablewidgetitem111)
        __qtablewidgetitem112 = QTableWidgetItem()
        self.tableWidget_9.setItem(0, 1, __qtablewidgetitem112)
        __qtablewidgetitem113 = QTableWidgetItem()
        self.tableWidget_9.setItem(0, 2, __qtablewidgetitem113)
        __qtablewidgetitem114 = QTableWidgetItem()
        self.tableWidget_9.setItem(1, 0, __qtablewidgetitem114)
        __qtablewidgetitem115 = QTableWidgetItem()
        self.tableWidget_9.setItem(1, 1, __qtablewidgetitem115)
        __qtablewidgetitem116 = QTableWidgetItem()
        self.tableWidget_9.setItem(1, 2, __qtablewidgetitem116)
        __qtablewidgetitem117 = QTableWidgetItem()
        self.tableWidget_9.setItem(2, 0, __qtablewidgetitem117)
        __qtablewidgetitem118 = QTableWidgetItem()
        self.tableWidget_9.setItem(2, 1, __qtablewidgetitem118)
        __qtablewidgetitem119 = QTableWidgetItem()
        self.tableWidget_9.setItem(2, 2, __qtablewidgetitem119)
        self.tableWidget_9.setObjectName(u"tableWidget_9")
        self.tableWidget_9.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.tableWidget_9.sizePolicy().hasHeightForWidth())
        self.tableWidget_9.setSizePolicy(sizePolicy2)
        self.tableWidget_9.setMaximumSize(QSize(301, 91))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_9.setPalette(palette7)
        self.tableWidget_9.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_9.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_9.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_9.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_9.horizontalHeader().setVisible(False)
        self.tableWidget_9.verticalHeader().setVisible(False)

        self.gridLayout.addWidget(self.tableWidget_9, 2, 2, 1, 1)

        self.tableWidget_4 = QTableWidget(self.layoutWidget)
        if (self.tableWidget_4.columnCount() < 3):
            self.tableWidget_4.setColumnCount(3)
        __qtablewidgetitem120 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem120)
        __qtablewidgetitem121 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem121)
        __qtablewidgetitem122 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem122)
        if (self.tableWidget_4.rowCount() < 3):
            self.tableWidget_4.setRowCount(3)
        __qtablewidgetitem123 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, __qtablewidgetitem123)
        __qtablewidgetitem124 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, __qtablewidgetitem124)
        __qtablewidgetitem125 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, __qtablewidgetitem125)
        __qtablewidgetitem126 = QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, __qtablewidgetitem126)
        __qtablewidgetitem127 = QTableWidgetItem()
        self.tableWidget_4.setItem(0, 1, __qtablewidgetitem127)
        __qtablewidgetitem128 = QTableWidgetItem()
        self.tableWidget_4.setItem(0, 2, __qtablewidgetitem128)
        __qtablewidgetitem129 = QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, __qtablewidgetitem129)
        __qtablewidgetitem130 = QTableWidgetItem()
        self.tableWidget_4.setItem(1, 1, __qtablewidgetitem130)
        __qtablewidgetitem131 = QTableWidgetItem()
        self.tableWidget_4.setItem(1, 2, __qtablewidgetitem131)
        __qtablewidgetitem132 = QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, __qtablewidgetitem132)
        __qtablewidgetitem133 = QTableWidgetItem()
        self.tableWidget_4.setItem(2, 1, __qtablewidgetitem133)
        __qtablewidgetitem134 = QTableWidgetItem()
        self.tableWidget_4.setItem(2, 2, __qtablewidgetitem134)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        sizePolicy1.setHeightForWidth(self.tableWidget_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_4.setSizePolicy(sizePolicy1)
        self.tableWidget_4.setMinimumSize(QSize(0, 0))
        self.tableWidget_4.setMaximumSize(QSize(301, 91))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        self.tableWidget_4.setPalette(palette8)
        self.tableWidget_4.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_4.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.tableWidget_4.setIconSize(QSize(0, 0))
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.verticalHeader().setMinimumSectionSize(0)

        self.gridLayout.addWidget(self.tableWidget_4, 1, 0, 1, 1)

        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(360, 350, 235, 89))
        self.gridLayout_2 = QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.difficultyLabel = QLabel(self.layoutWidget1)
        self.difficultyLabel.setObjectName(u"difficultyLabel")

        self.horizontalLayout.addWidget(self.difficultyLabel)

        self.difficultyBox = QComboBox(self.layoutWidget1)
        self.difficultyBox.addItem("")
        self.difficultyBox.addItem("")
        self.difficultyBox.addItem("")
        self.difficultyBox.addItem("")
        self.difficultyBox.setObjectName(u"difficultyBox")

        self.horizontalLayout.addWidget(self.difficultyBox)


        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.solveButton = QPushButton(self.layoutWidget1)
        self.solveButton.setObjectName(u"solveButton")

        self.gridLayout_2.addWidget(self.solveButton, 2, 1, 1, 1)

        self.resetButton = QPushButton(self.layoutWidget1)
        self.resetButton.setObjectName(u"resetButton")

        self.gridLayout_2.addWidget(self.resetButton, 1, 0, 1, 1)

        self.newButton = QPushButton(self.layoutWidget1)
        self.newButton.setObjectName(u"newButton")

        self.gridLayout_2.addWidget(self.newButton, 2, 0, 1, 1)

        self.mistakes = QLabel(self.layoutWidget1)
        self.mistakes.setObjectName(u"mistakes")

        self.gridLayout_2.addWidget(self.mistakes, 0, 1, 1, 1)

        self.mistakesLabel = QLabel(self.layoutWidget1)
        self.mistakesLabel.setObjectName(u"mistakesLabel")
        self.mistakesLabel.setTextFormat(Qt.AutoText)
        self.mistakesLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.mistakesLabel, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.resetButton.clicked.connect(MainWindow.resetBoard)
        self.tableWidget_2.cellChanged.connect(MainWindow.editCell)
        self.tableWidget.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_3.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_4.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_5.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_6.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_7.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_8.cellChanged.connect(MainWindow.editCell)
        self.tableWidget_9.cellChanged.connect(MainWindow.editCell)
        self.newButton.clicked.connect(MainWindow.newBoard)
        self.solveButton.clicked.connect(MainWindow.autoSolve)
        self.difficultyBox.currentIndexChanged.connect(MainWindow.selectDifficulty)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        ___qtablewidgetitem = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem1 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem2 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem3 = self.tableWidget_2.verticalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem4 = self.tableWidget_2.verticalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem5 = self.tableWidget_2.verticalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)

        ___qtablewidgetitem6 = self.tableWidget_7.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem7 = self.tableWidget_7.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem8 = self.tableWidget_7.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem9 = self.tableWidget_7.verticalHeaderItem(0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem10 = self.tableWidget_7.verticalHeaderItem(1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem11 = self.tableWidget_7.verticalHeaderItem(2)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled1 = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        self.tableWidget_7.setSortingEnabled(__sortingEnabled1)

        ___qtablewidgetitem12 = self.tableWidget_8.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem13 = self.tableWidget_8.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem14 = self.tableWidget_8.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem15 = self.tableWidget_8.verticalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem16 = self.tableWidget_8.verticalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem17 = self.tableWidget_8.verticalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled2 = self.tableWidget_8.isSortingEnabled()
        self.tableWidget_8.setSortingEnabled(False)
        self.tableWidget_8.setSortingEnabled(__sortingEnabled2)

        ___qtablewidgetitem18 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem19 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem20 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem21 = self.tableWidget_3.verticalHeaderItem(0)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem22 = self.tableWidget_3.verticalHeaderItem(1)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem23 = self.tableWidget_3.verticalHeaderItem(2)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled3 = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled3)

        ___qtablewidgetitem24 = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem25 = self.tableWidget_5.horizontalHeaderItem(1)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem26 = self.tableWidget_5.horizontalHeaderItem(2)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem27 = self.tableWidget_5.verticalHeaderItem(0)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem28 = self.tableWidget_5.verticalHeaderItem(1)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem29 = self.tableWidget_5.verticalHeaderItem(2)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled4 = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        self.tableWidget_5.setSortingEnabled(__sortingEnabled4)

        ___qtablewidgetitem30 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem31 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem32 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem33 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem34 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem35 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled5 = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled5)

        ___qtablewidgetitem36 = self.tableWidget_6.horizontalHeaderItem(0)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem37 = self.tableWidget_6.horizontalHeaderItem(1)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem38 = self.tableWidget_6.horizontalHeaderItem(2)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem39 = self.tableWidget_6.verticalHeaderItem(0)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem40 = self.tableWidget_6.verticalHeaderItem(1)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem41 = self.tableWidget_6.verticalHeaderItem(2)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled6 = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        self.tableWidget_6.setSortingEnabled(__sortingEnabled6)

        ___qtablewidgetitem42 = self.tableWidget_9.horizontalHeaderItem(0)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem43 = self.tableWidget_9.horizontalHeaderItem(1)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem44 = self.tableWidget_9.horizontalHeaderItem(2)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem45 = self.tableWidget_9.verticalHeaderItem(0)
        ___qtablewidgetitem45.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem46 = self.tableWidget_9.verticalHeaderItem(1)
        ___qtablewidgetitem46.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem47 = self.tableWidget_9.verticalHeaderItem(2)
        ___qtablewidgetitem47.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled7 = self.tableWidget_9.isSortingEnabled()
        self.tableWidget_9.setSortingEnabled(False)
        self.tableWidget_9.setSortingEnabled(__sortingEnabled7)

        ___qtablewidgetitem48 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem48.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem49 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem49.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem50 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem50.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem51 = self.tableWidget_4.verticalHeaderItem(0)
        ___qtablewidgetitem51.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem52 = self.tableWidget_4.verticalHeaderItem(1)
        ___qtablewidgetitem52.setText(QCoreApplication.translate("MainWindow", u"New Row", None));
        ___qtablewidgetitem53 = self.tableWidget_4.verticalHeaderItem(2)
        ___qtablewidgetitem53.setText(QCoreApplication.translate("MainWindow", u"New Row", None));

        __sortingEnabled8 = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled8)

        self.difficultyLabel.setText(QCoreApplication.translate("MainWindow", u"Difficulty:", None))
        self.difficultyBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Easy", None))
        self.difficultyBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Medium", None))
        self.difficultyBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Hard", None))
        self.difficultyBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Expert", None))

        self.solveButton.setText(QCoreApplication.translate("MainWindow", u"Solve", None))
        self.resetButton.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.newButton.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.mistakes.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.mistakesLabel.setText(QCoreApplication.translate("MainWindow", u"Mistakes:", None))
    # retranslateUi

